export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const FETCH_SEMESTERS = "FETCH_SEMESTERS";
export const FETCH_INSTRUCTORS = "FETCH_INSTRUCTORS";
export const FETCH_OFFERINGS = "FETCH_OFFERINGS";
export const SELECT_SEMESTER = "SELECT_SEMESTER";
export const ADD_INSTRUCTOR = "ADD_INSTRUCTOR";
export const DELETE_INSTRUCTOR = "DELETE_INSTRUCTOR";